### ISSUE TITLE
Feature request: Individual left/right volume adjustment control

### ISSUE THREAD

**Issue by itsspher** [saumya-banthia/volume-boost#1]
Since your plugin interfaces directly with PulseAudio, could you implement individual left/right audio control? I'm a person who needs to adjust balance in my audio due to a genetic hearing disorder, and as of current, the only way to do that in gaming mode is to boot up pavucontrol as a non-steam game. Your plugin could be really good for gamers like me who need this specific accessibility feature.

**Comment by saumya-banthia** [comment]
Hi, I had a rough few months. Took some time off. I'd definitely be down to build this into the plugin, I'll let you know once it is done.

**Comment by saumya-banthia** [comment]
Feature addition with https://github.com/saumya-banthia/volume-boost/commit/bc34586583cb02fd69a999ab494ba2ae8f1ef82e
