### ISSUE TITLE
Plugin Doesn't Launch on Steam Deck Beta Client

### ISSUE THREAD

**Issue by TopHatHipster** [saumya-banthia/volume-boost#2]
After a small check on the latest Deck Beta Client, I noticed several plugins not starting at all and figured to let the current maintainers of those plugins know.

Your `volume-boost` plugin has been affected as well. Since the plugin doesn't have any plugin-support thread on the Decky Loader Discord, nor could I quickly find any Discord user in the server that resembles the maintainer, I figured notifying the project maintainers through the repository itself.

---

If the plugin hasn't been migrated over to a global DFL yet, I'd highly recommend doing so as that might fix the issue (although I'm unsure of that).

Tested Steam Deck Client version is `1711734008`, `Fri Mar 29 17:09 UTC` is the build date.

**Comment by saumya-banthia** [comment]
Commit https://github.com/saumya-banthia/volume-boost/commit/7277fe70f0af662437605fe24621791e7c19505f migrates to global DFL. Check and report here: https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/599 once it goes to testing/release.

Closing for now.
